---
grails:
    profile: plugin
    codegen:
        defaultPackage: logback.appender
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    activemq:
        brokerUrl: 'tcp://localhost:61716'
        pooled: true
